import { z } from 'zod'

// A bill sundry is a charge or a deduction that applies to the whole invoice rather than to
// one line: freight, packing, insurance, a discount, and — in bill-wise tax mode — the tax
// itself. There are two shapes here and they are not the same thing:
//
//   the MASTER entry — what this charge IS, kept between invoices and shared by everyone
//   the ROW          — what this invoice charged, and what the operator typed
//
// The master owns everything the operator may not change on a single invoice, which is why
// `kind` and `taxable` live there and not on the row. A freight that is a percentage on one
// invoice and a flat amount on the next is not one charge, it is two.

/** How the amount is worked out. Fixed by the master entry: the operator picks it once, when
 * the charge is invented, and it is written back to the master there and then. */
export const sundryKindSchema = z.enum(['percent', 'flat', 'perUnit'])

/** Which tax this row IS, for the rows bill-wise mode generates. `null` for every ordinary
 * charge, which is nearly all of them. */
export const taxComponentSchema = z.enum(['cgst', 'sgst', 'igst', 'cess'])

export const sundryMasterSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  kind: sundryKindSchema,
  /** Suggested when the charge is picked. The operator may type over it on the invoice. */
  defaultValue: z.number(),
  /** Whether tax is charged ON this charge. Freight billed by the supplier is part of the
   * taxable value under GST, so freight taxed at the rate of the goods it carries is the
   * normal case, not the exception — which is why every seeded entry is taxable and the
   * field exists anyway. Somebody has to be able to say no eventually. */
  taxable: z.boolean(),
  /** Set only on the tax components themselves. A row carrying one of these is generated by
   * the invoice, never chosen by hand, and item-level tax modes refuse it outright — tax
   * lives in one place per invoice or the two places disagree. */
  taxComponent: taxComponentSchema.nullable(),
})

export const sundryRowSchema = z.object({
  id: z.string().min(1),
  /** Null on a blank row waiting to be typed into, the same as an item row with no item. */
  sundryId: z.string().nullable(),
  name: z.string(),
  kind: sundryKindSchema,
  /** A percentage when the kind is percent, otherwise paise — of the whole charge for flat,
   * or per unit of goods for perUnit. */
  value: z.number(),
  /** What it came to. Held rather than derived, for the same reason a row's amount is. */
  amountPaise: z.number().int(),
  taxable: z.boolean(),
  taxComponent: taxComponentSchema.nullable(),
})

export type SundryKind = z.infer<typeof sundryKindSchema>
export type TaxComponent = z.infer<typeof taxComponentSchema>
export type SundryMaster = z.infer<typeof sundryMasterSchema>
export type SundryRow = z.infer<typeof sundryRowSchema>

/** A blank sundry row. Two of these open the sundry grid, and another appears when the cursor
 * reaches the last — the same rule the item grid follows. */
export function emptySundryRow(id: string): SundryRow {
  return { id, sundryId: null, name: '', kind: 'flat', value: 0, amountPaise: 0, taxable: true, taxComponent: null }
}
