// The mock world behind the one interface. Replaced whole by a backend implementation later.

import type { DataAdapter } from '../adapter'
import { refuse } from '../schema/refusal'
import { items } from './items'
import { invoiceOf } from './lines'
import { insightsOf } from './insights'
import { kindOf } from '../../lib/attachments'
import { today as todayIs } from '../../lib/day'
import { invoices } from './invoices'
import { parties, recentPartyIds } from './parties'
import { lastUsedByParty, sundryMaster } from './sundries'
import { slowly } from './slowly'
import { headerFor, invoiceNumberFor } from './invoices'
import { refuseTheSave } from './switches'

/** Search by name, alias or barcode, which is what the item column has to do. */
function matches(item: (typeof items)[number], search: string) {
  const needle = search.trim().toLowerCase()
  if (needle === '') return true
  return (
    item.name.toLowerCase().includes(needle) ||
    item.alias.toLowerCase().includes(needle) ||
    item.barcode.includes(needle)
  )
}

const answers: DataAdapter = {
  async listItems(search) {
    return items.filter((item) => matches(item, search)).slice(0, 50)
  },

  async listParties(search) {
    const needle = search.trim().toLowerCase()
    // Name, mobile and GSTIN. City is shown on every row and searched by none of them.
    return parties
      .filter(
        (party) =>
          needle === '' ||
          party.name.toLowerCase().includes(needle) ||
          party.mobile.includes(needle) ||
          party.gstin.toLowerCase().includes(needle),
      )
      .slice(0, 50)
  },

  async createParty(draft) {
    // Whether a party is ALLOWED to exist — the name already taken, the GSTIN real — is the
    // backend's call, and this stands in for a yes.
    //
    // THE STANDING OF A GSTIN IS NOT DECIDED HERE EITHER, and least of all by whether the box
    // was empty. A new party has no history: no grade, no limit, nothing overdue, and a
    // registration nobody has checked. `unchecked` is the honest answer and it is what a real
    // backend would return until the portal has been asked.
    return {
      ...draft,
      id: `party-new-${parties.length}`,
      outstandingPaise: 0,
      trustGrade: null,
      creditLimitPaise: 0,
      // A party created at the counter has agreed no terms yet, which is not the same as being
      // due immediately. Whoever opens the master sets them.
      creditDays: 0,
      overduePaise: 0,
      gstinStatus: 'unchecked',
    }
  },

  async partyInsights(partyId: string) {
    const party = parties.find((candidate) => candidate.id === partyId)
    if (party === undefined) return refuse('missing', 'That party is not on file any more.')
    return insightsOf(party, todayIs())
  },

  async invoiceSettings() {
    return {
      // The company's default. Whatever the settings drawer says wins over it the moment the
      // screen mounts — the drawer is the one source, and `?tax=` seeds THAT rather than this,
      // or the two disagree by a frame and the switch looks broken.
      taxMode: 'itemExclusive' as const,
      roundOff: { stepPaise: 100, method: 'nearest' as const, on: true },
      columns: { discount: false, alias: false, hsn: false, mrp: false, freeQuantity: false },
      roundEachLine: false,
      hsnWiseSummary: false,
      // Madhya Pradesh. Half the seeded parties are elsewhere, so both CGST+SGST and IGST
      // happen without anybody having to arrange them.
      companyStateCode: '23',
    }
  },

  async listSundries(search) {
    const needle = search.trim().toLowerCase()
    // The tax components are generated by the invoice, never picked, so they are not offered.
    return sundryMaster
      .filter((sundry) => sundry.taxComponent === null)
      .filter((sundry) => needle === '' || sundry.name.toLowerCase().includes(needle))
  },

  async createSundry(draft) {
    return { ...draft, id: `sundry-new-${sundryMaster.length}` }
  },

  async lastUsedSundries(partyId) {
    const ids = lastUsedByParty[partyId] ?? []
    return ids.map((id) => sundryMaster.find((sundry) => sundry.id === id)).filter((sundry) => sundry !== undefined)
  },

  async listRecentParties() {
    return recentPartyIds
      .map((id) => parties.find((party) => party.id === id))
      .filter((party) => party !== undefined)
  },

  // A running number in the current financial year, the way v2 shows it: 4/2026-27 — and the
  // shape comes from `invoiceNumberFor`, which is also what the seeded book and `saveInvoice`
  // use. There were two shapes: this one offered `68/2026-27` and the save handed back
  // `INV/2026/0068`, so the number changed shape at the moment it became real.
  //
  // THE SERIES NAME IS NEVER IN THE NUMBER. This appended " (Export)" to anything but the main
  // book, which put the series in the one place both Aj and the product document say it must
  // not be: "The field label is 'Inv No'. No separate Series field or Series name is shown."
  // The series lives in the label's own list and nowhere else — a number with a word in it is
  // a number nobody can file under.
  //
  // Each book counts separately, which is the whole point of having more than one.
  async nextInvoiceNumber(series: string) {
    const already = invoices.length + (series === 'Main' ? 1 : 64)
    return invoiceNumberFor(already)
  },

  async listInvoices(query) {
    const needle = query.search.trim().toLowerCase()
    return invoices.filter(
      (invoice) =>
        needle === '' ||
        invoice.number.toLowerCase().includes(needle) ||
        invoice.partyName.toLowerCase().includes(needle),
    )
  },

  async getInvoice(id) {
    const saved = invoices.find((invoice) => invoice.id === id)
    if (saved) return saved

    // `?rows=2000` asks for an invoice of that size rather than a saved one. It is how the
    // grid is measured, and it is mock-only.
    const requested = Number.parseInt(id.replace(/\D/g, ''), 10)
    const size = Number.isFinite(requested) ? requested : 10
    return { ...invoices[1]!, id: `invoice-of-${size}`, ...invoiceOf(size) }
  },

  async lastInvoiceDate() {
    // The newest date across the book. The real backend answers this from an index rather than
    // by reading every invoice, which is the whole reason it is asked rather than worked out.
    const dates = invoices.map((invoice) => invoice.date).sort()
    return dates[dates.length - 1] ?? null
  },

  // WHO IS SIGNED IN IS THE BACKEND'S ANSWER, and the mock is the only place in this build
  // that has one at all — the shell has a ROLE switch (owner / operator) and no person behind
  // it. So the name here is a stand-in for a session the front end will never own, and
  // docs/backend-assumptions.md says so to the dev team.
  //
  // THE CLOCK IS THE SERVER'S TOO, and this is the seam where that stops being pretend. The
  // mock reads the machine's clock because it has nothing else; a real one must not.
  async attachFile(name, bytes) {
    return {
      id: `attachment-${name}-${String(bytes)}`,
      name,
      kind: kindOf(name) ?? 'File',
      bytes,
      attachedBy: 'Aj Sharma',
      attachedAt: new Date().toISOString(),
    }
  },

  async saveInvoice(draft) {
    // The mock keeps nothing. It can be told to come back refused with `?refuse`, so that the
    // refusal state is designed and looked at rather than discovered on the day a real backend
    // first says no. The reason below stands in for THEIR decision, not a rule of ours — see
    // docs/backend-assumptions.md.
    if (refuseTheSave()) {
      // IT NAMES THE FIELD, AND UNTIL 24-08 NOTHING EVER DID. `Refusal.field` exists so the
      // screen can put the cursor on the thing to correct — docs/backend-assumptions.md
      // promises the dev team exactly that — and the mock never set it, so the one refusal
      // anybody could look at was the one kind of refusal the field does not help with. A
      // promise the sample data cannot demonstrate is a promise nobody has tested.
      //
      // The reason stands in for THEIR decision, not a rule of ours: a credit limit is the
      // backend's to enforce and the wording is theirs to write.
      return refuse(
        'save-refused',
        'This party is over its credit limit. Reduce the invoice or take a payment against the outstanding first.',
        'party',
      )
    }
    // THE BACKEND DECIDES THE NUMBER AND THE DATES. That is the whole reason a draft does not
    // carry them, and the reason a screen must read what comes back rather than what it sent.
    const today = '2026-08-21'
    return {
      ...draft,
      id: `invoice-${invoices.length + 1}`,
      number: invoiceNumberFor(invoices.length + 1),
      date: today,
      dueDate: today,
      // AND THE BACKEND DECIDES WHAT IT IS WORTH. The draft does not carry these for the same
      // reason it does not carry the number: they are the backend's answer, not the screen's.
      //
      // ALL THREE FROM ONE PLACE. The total used to be worked out separately, right here, as
      // the sum of the line amounts — which is the TAXABLE value. So a save handed back an
      // invoice whose total was its own sub-total with the tax missing, and the listing then
      // showed it that way.
      ...headerFor(draft.rows),
      paidPaise: 0,
      cancelledAt: null,
    }
  },
}

// One wrapper, applied once, around everything.
export const mockAdapter: DataAdapter = slowly(answers)
