// The mock world behind the one interface. Replaced whole by a backend implementation later.

import type { DataAdapter } from '../adapter'
import { refuse } from '../schema/refusal'
import { items } from './items'
import { invoiceOf } from './lines'
import { insightsOf } from './insights'
import { today as todayIs } from '../../lib/day'
import { invoices } from './invoices'
import { parties, recentPartyIds } from './parties'
import { lastUsedByParty, sundryMaster } from './sundries'
import { slowly } from './slowly'
import { summed } from './invoices'
import { refuseTheSave } from './switches'

/** Search by name, alias or barcode, which is what the item column has to do. */
function matches(item: (typeof items)[number], search: string) {
  const needle = search.trim().toLowerCase()
  if (needle === '') return true
  return (
    item.name.toLowerCase().includes(needle) ||
    item.alias.toLowerCase().includes(needle) ||
    item.barcode.includes(needle)
  )
}

const answers: DataAdapter = {
  async listItems(search) {
    return items.filter((item) => matches(item, search)).slice(0, 50)
  },

  async listParties(search) {
    const needle = search.trim().toLowerCase()
    // Name, mobile and GSTIN. City is shown on every row and searched by none of them.
    return parties
      .filter(
        (party) =>
          needle === '' ||
          party.name.toLowerCase().includes(needle) ||
          party.mobile.includes(needle) ||
          party.gstin.toLowerCase().includes(needle),
      )
      .slice(0, 50)
  },

  async createParty(draft) {
    // Whether a party is ALLOWED to exist — the name already taken, the GSTIN real — is the
    // backend's call, and this stands in for a yes.
    //
    // THE STANDING OF A GSTIN IS NOT DECIDED HERE EITHER, and least of all by whether the box
    // was empty. A new party has no history: no grade, no limit, nothing overdue, and a
    // registration nobody has checked. `unchecked` is the honest answer and it is what a real
    // backend would return until the portal has been asked.
    return {
      ...draft,
      id: `party-new-${parties.length}`,
      outstandingPaise: 0,
      trustGrade: null,
      creditLimitPaise: 0,
      overduePaise: 0,
      gstinStatus: 'unchecked',
    }
  },

  async partyInsights(partyId: string) {
    const party = parties.find((candidate) => candidate.id === partyId)
    if (party === undefined) return refuse('missing', 'That party is not on file any more.')
    return insightsOf(party, todayIs())
  },

  async invoiceSettings() {
    return {
      // The company's default. Whatever the settings drawer says wins over it the moment the
      // screen mounts — the drawer is the one source, and `?tax=` seeds THAT rather than this,
      // or the two disagree by a frame and the switch looks broken.
      taxMode: 'itemExclusive' as const,
      roundOff: { stepPaise: 100, method: 'nearest' as const, on: true },
      columns: { discount: false, alias: false, hsn: false, mrp: false, freeQuantity: false },
      roundEachLine: false,
      hsnWiseSummary: false,
      // Madhya Pradesh. Half the seeded parties are elsewhere, so both CGST+SGST and IGST
      // happen without anybody having to arrange them.
      companyStateCode: '23',
    }
  },

  async listSundries(search) {
    const needle = search.trim().toLowerCase()
    // The tax components are generated by the invoice, never picked, so they are not offered.
    return sundryMaster
      .filter((sundry) => sundry.taxComponent === null)
      .filter((sundry) => needle === '' || sundry.name.toLowerCase().includes(needle))
  },

  async createSundry(draft) {
    return { ...draft, id: `sundry-new-${sundryMaster.length}` }
  },

  async lastUsedSundries(partyId) {
    const ids = lastUsedByParty[partyId] ?? []
    return ids.map((id) => sundryMaster.find((sundry) => sundry.id === id)).filter((sundry) => sundry !== undefined)
  },

  async listRecentParties() {
    return recentPartyIds
      .map((id) => parties.find((party) => party.id === id))
      .filter((party) => party !== undefined)
  },

  // A running number in the current financial year, the way v2 shows it: 4/2026-27.
  //
  // THE SERIES NAME IS NEVER IN THE NUMBER. This appended " (Export)" to anything but the main
  // book, which put the series in the one place both Aj and the product document say it must
  // not be: "The field label is 'Inv No'. No separate Series field or Series name is shown."
  // The series lives in the label's own list and nowhere else — a number with a word in it is
  // a number nobody can file under.
  //
  // Each book counts separately, which is the whole point of having more than one.
  async nextInvoiceNumber(series: string) {
    const already = invoices.length + (series === 'Main' ? 1 : 64)
    return `${already}/2026-27`
  },

  async listInvoices(query) {
    const needle = query.search.trim().toLowerCase()
    return invoices.filter(
      (invoice) =>
        needle === '' ||
        invoice.number.toLowerCase().includes(needle) ||
        invoice.partyName.toLowerCase().includes(needle),
    )
  },

  async getInvoice(id) {
    const saved = invoices.find((invoice) => invoice.id === id)
    if (saved) return saved

    // `?rows=2000` asks for an invoice of that size rather than a saved one. It is how the
    // grid is measured, and it is mock-only.
    const requested = Number.parseInt(id.replace(/\D/g, ''), 10)
    const size = Number.isFinite(requested) ? requested : 10
    return { ...invoices[1]!, id: `invoice-of-${size}`, ...invoiceOf(size) }
  },

  async saveInvoice(draft) {
    // The mock keeps nothing. It can be told to come back refused with `?refuse`, so that the
    // refusal state is designed and looked at rather than discovered on the day a real backend
    // first says no. The reason below stands in for THEIR decision, not a rule of ours — see
    // docs/backend-assumptions.md.
    if (refuseTheSave()) {
      return refuse('save-refused', 'This invoice was not accepted. Check it and try again.')
    }
    // THE BACKEND DECIDES THE NUMBER AND THE DATES. That is the whole reason a draft does not
    // carry them, and the reason a screen must read what comes back rather than what it sent.
    const today = '2026-08-21'
    return {
      ...draft,
      id: `invoice-${invoices.length + 1}`,
      number: `INV/2026/${String(invoices.length + 1).padStart(4, '0')}`,
      date: today,
      dueDate: today,
      // AND THE BACKEND DECIDES WHAT IT IS WORTH. The draft does not carry these for the same
      // reason it does not carry the number: they are the backend's answer, not the screen's.
      ...summed(draft.rows),
      totalPaise: draft.rows.reduce((running, row) => running + row.amountPaise, 0),
      paidPaise: 0,
      cancelledAt: null,
    }
  },
}

// One wrapper, applied once, around everything.
export const mockAdapter: DataAdapter = slowly(answers)
